### ISSUE TITLE
Multilanguage support not working

### ISSUE THREAD

**Issue by VolkovIlia** [gethugothemes/academia-hugo#44]
After uncommenting `config/_default/languages.toml`

```toml
# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
languageCode = "zh-Hans"
contentDir = "content/zh"
title = "Chinese website title..."
[zh.params]
  description = "Site description in Chinese..."
[[zh.menu.main]]
  name = "Wo"
  url = "#about"
  weight = 1
```
got Error:

```
Error: error building site: render: failed to render pages: render of "/" failed: "/home/volk/Downloads/source/academia-hugo/themes/academia-hugo/layouts/_default/baseof.html:10:5": execute of template failed: template: index.html:10:5: executing "index.html" at <partial "navbar.html" .>: error calling partial: "/home/volk/Downloads/source/academia-hugo/themes/academia-hugo/layouts/partials/navbar.html:112:74": execute of template failed: template: partials/navbar.html:112:74: executing "partials/navbar.html" at <.URL>: can't evaluate field URL in type page.Page
```

How to fix?

P.s. Also link `https://sourcethemes.com/academic/docs/language/` go to broken webpage.
